### ISSUE TITLE
Selecting blobs always returns nil

### ISSUE THREAD

**Issue by fabioxgn** [nakagami/firebirdsql#10]
```Go
rows, _ := conn.Query("SELECT BLOB_FIELD FROM MY_TABLE")
for rows.Next() {
	var blob sql.RawBytes
	rows.Scan(&blob)
	println(blob)
}
```

This outputs: `[0/0]0x0`

Am I doing it wrong? 

Firebird 2.5.2 on Windows.

**Comment by nakagami** [comment]
Now fixed and I think you can fetch blob values.
Please test with latest version.

But, I have found one problem in your code with recent (master) golang repository. 
Recent golang can't Scan with sql.RawBytes, So I use []byte

**Comment by fabioxgn** [comment]
@nakagami  Thanks. I tested it and now the blobs are returning, but I'm getting this error:

```6765
6769
6742
6762
6761
6766
6767
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/nakagami/firebirdsql.(*wireProtocol).getBlobSegments(0x120fe370, 0x120f3470, 0x8, 0x8, 0x1, 0x0, 0x0, 0x0, 0x
0, 0x0)
        E:/dev/go/src/github.com/nakagami/firebirdsql/wireprotocol.go:447 +0x37b
github.com/nakagami/firebirdsql.(*firebirdsqlRows).Next(0x120f5ea0, 0x121101c8, 0x1, 0x1, 0x0, 0x0)
        E:/dev/go/src/github.com/nakagami/firebirdsql/rows.go:101 +0x3ff
database/sql.(*Rows).Next(0x120f8480, 0x0)
        c:/go/src/database/sql/sql.go:1592 +0xf6
main.main()
        E:/dev/go/src/github.com/monde-sistemas/anexos/main.go:17 +0x13d```

The code I'm using is the following:

```Go
	rows, _ := conn.Query("SELECT BLOB_FIELD FROM MY_TABLE")
	for rows.Next() {
		var blob []byte
		rows.Scan(&blob)
		println(len(blob))
	}
```

Notice that the length of the first itens are printed, then there is the error. I thought that it was a null value but I checked the database and there is 36 records, all of them with values on the blob field.

**Comment by nakagami** [comment]
Sorry, probably fix it. Please retry.

**Comment by fabioxgn** [comment]
@nakagami Hi, I tested again and now it's working properly. Thanks :)

**Comment by nakagami** [comment]
Thaks
