### ISSUE TITLE
Firebird Event : Unsupported Family Protocol 17

### ISSUE THREAD

**Issue by chiangkl** [nakagami/firebirdsql#110]
I am trying to connect to Firebird to monitor an event, the following code produce error "Unsupported Family Protocol 17". (I am using Firebird 3.0.5)

```
	sbr, err := fbEvent.Subscribe(events, func(event firebirdsql.Event) { //or use SubscribeChan
      	  fmt.Printf("event: %s, count: %d, id: %d, remote id:%d \n", event.Name, event.Count, event.ID, event.RemoteID)
        })
	if err != nil {
		fmt.Printf("err")
	}
```

Is this library work well with Firebird 3.0.5.

**Comment by nakagami** [comment]
It looks like a network configuration issue.
Is that Windows box ?

**Comment by chiangkl** [comment]
Yes, it is a windows 7 box.

**Comment by nakagami** [comment]
Sorry, I don't why, but I think it might have something to do with the netbios settings

**Comment by kamhlos** [comment]
Hi, thanks for your work! It works perfect so far! :)
I'm also getting this error when using fbEvent.SubscribeChan
Trying to connect to a windows 7 x64 server. You said something about NETBIOS, though a quick search didn't show much.
Can you provide more info?

**Comment by l-express** [comment]
I also got this problem on several computers under Windows. It doesn't look like it's related to netbios settings

1. It seems that the syscall.AF_INET != family check is not needed for correct operation.
2. The second problem was that the ip address parameters for some reason were not in 4,5,6,7 bytes, but in 20,21,22,23 bytes of the buffer.

func (s *Subscription) connAuxRequest() (int32, *net.IP, int, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.fc.wp.opConnectRequest()
	auxHandle, _, buf, err := s.fc.wp.opResponse()
	if err != nil {
		return -1, nil, 0, err
	}
	//	family := bytes_to_int16(buf[0:2])
	port := binary.BigEndian.Uint16(buf[2:4])
	//	ip := net.IPv4(buf[4], buf[5], buf[6], buf[7])
	ip := net.IPv4(buf[20], buf[21], buf[22], buf[23])

	//	if syscall.AF_INET != family {
	//		return -1, nil, 0, fmt.Errorf("unsupported  family protocol: %x", family)
	//	}

	return auxHandle, &ip, int(port), nil
}

After the specified changes in the code, everything works fine. I checked under the Windows operating system with Firebird 3 and Firebird 5. I did not check these changes under Linux.

**Comment by nakagami** [comment]
I believe this is fixed in this commit https://github.com/nakagami/firebirdsql/commit/29d18e480b0987fb87fbe7ade66560072601269b
Could you try it in master HEAD?

**Comment by l-express** [comment]
I have very little experience with Golang. Under Windows, the constant syscall.AF_IRDA is unknown. I don't know what dependency to add to the package. If you comment this constant, everything builds and works fine

**Comment by nakagami** [comment]
I understand.
Adding AF_IRDA was a simple mistake on my part.

Is this correct? https://github.com/nakagami/firebirdsql/commit/0ec686eba0f9cefc009c437a88bf0f0778c818be

**Comment by l-express** [comment]
Yes, everything is fine. Thank you so much for your work
