### ISSUE TITLE
Value uint64 converts into negative int32 while stored into BIGINT field

### ISSUE THREAD

**Issue by KenSv** [nakagami/firebirdsql#112]
Sample code:
var val uint64
	val = 2147483648
	tx, err := db.Begin()
	if err != nil {
		tx.Rollback()
	}
	_, err = tx.Exec("insert into test(B1) values(?)", val)
	if err != nil {
		fmt.Println(err)
	}
	tx.Commit()
Firebird DDL:
CREATE TABLE TEST (
    B1  BIGINT
);
Result: B1 = -2147483648
if value = 2147483647, result is positive = 2147483647

**Comment by nakagami** [comment]
use blr_int64
https://github.com/FirebirdSQL/firebird/blob/master/src/include/firebird/impl/blr.h#L44

**Comment by nakagami** [comment]
Thanks for your report

**Comment by KenSv** [comment]
Thank you so much! It's working correct
