### ISSUE TITLE
Charset params 

### ISSUE THREAD

**Issue by RafaMnzs** [nakagami/firebirdsql#116]
Hi everyone, i try connect to database but the drive send me a message "CHARACTER SET UTF8 is not defined". 

My string connection has the follows params: **SYSDBA:masterkey@localhost/C:/Bancos/omega/SISTDADO.FDB?charset=UTF8**

The params is correct?

**Comment by nakagami** [comment]
Is your Firebird version 2.1 or earlier?

**Comment by nakagami** [comment]
merged pull request https://github.com/nakagami/firebirdsql/pull/109
