### ISSUE TITLE
Slow Queries Compared to FlameRobin and isql-fb

### ISSUE THREAD

**Issue by krixano** [nakagami/firebirdsql#119]
So, I'm getting weird results with a query. When I run this query in FlameRobin, it takes about 400ms, but when I run it using this library in golang, it takes up to 5-6 seconds (the query *alone* - this doesn't include calling Scan). I don't really know what's causing this big difference.

The Query:
```sql
SELECT r.id, r.url, r.urlhash, r.scheme, r.domainid, r.contenttype, r.charset, r.language, r.title, r.prompt, r.size,
r.hash, r.feed, r.publishdate, r.indextime, r.album, r.artist, r.albumartist, r.composer, r.track, r.disc,
r.copyright, r.crawlindex, r.date_added, r.hidden
FROM (
    SELECT internal.*, (SELECT MAX(RANK) FROM keywords WHERE pageid=internal.id AND keywords.keyword LIKE ?) as searchrank
    FROM PAGES internal
) r
WHERE r.searchrank IS NOT NULL 
OR (replace(lower(url), 'gemini://', '') LIKE ? OR lower(title) LIKE ? OR lower(artist) LIKE ? 
OR lower(album) LIKE ? OR lower(albumartist) LIKE ?)
ORDER BY r.searchrank DESC
```

**Comment by bat22** [comment]
May be you execute already prepared query in flamerobin.
Can you separate prepare and exec time for this query?

**Comment by krixano** [comment]
I did the query in the terminal sql tool (isql-fb) and it was *very* quick as well, on first run and subsequent runs.
The prepared query should be handled under the hood by golang's sql library, afaik.

**Comment by krixano** [comment]
Oh, also, flamerobin shows the prepare happened in .013 seconds, and the execute happens in .400 seconds.

**Comment by nakagami** [comment]
The driver only implements methods that are predetermined, so it will be difficult to make it faster.

**Comment by nakagami** [comment]
It does not appear to be an effect of driver.
This is an old ticket and will be closed.
