### ISSUE TITLE
cyrillic connection path

### ISSUE THREAD

**Issue by alikxus** [nakagami/firebirdsql#124]
Hi, if i have directory with cyrillic symbols, do i have opportunities work with date base inside that directory? when i want connect to the database i get error - 
 I/O error during "CreateFile (open)" operation for file "D:\ДИРЕКТОРИЯ\test.FDB"
Error while trying to open file

ДИРЕКТОРИЯ - this is a cyrillic directory 
if i check it  - 
_, err := os.Stat(path); os.IsNotExist(err)
i do not have any errors.
Also  i connect to my database with any SQL client and do not have any errors

**Comment by nakagami** [comment]
Sorry I don't know how to treat non us-ascii file names.
