### ISSUE TITLE
Support for changing lock resolution params (WAIT | NO_WAIT)

### ISSUE THREAD

**Issue by strobil** [nakagami/firebirdsql#126]
Hi there!
It will be cool if the firebirdsql driver will have support for changing these [params](https://ib-aid.com/en/transactions-in-firebird-acid-isolation-levels-deadlocks-and-update-conflicts-resolution/#resolution).
Apparently the standard sql.TxOptions does not provide required fields to pass this option to firebirdsql driver.

Any ideas how to solve this?

**Comment by nakagami** [comment]
IsolationLevel の値を見てください
https://golang.org/pkg/database/sql/#IsolationLevel

全てをサポートはしてませんが、できる限りの transaction level を設定しています
https://github.com/nakagami/firebirdsql/blob/master/driver_go18.go#L62
