### ISSUE TITLE
SetMaxIdleConns(nIdle)  & SetMaxOpenConns(nOpen)  nIdle >0 && nOpen => nIdle seem to be not working

### ISSUE THREAD

**Issue by andrewkip** [nakagami/firebirdsql#137]
Hello!  
There is no effect if I try limit MaxOpenConns  and MaxIdleConns - open connections are not limited.
But if I call SetMaxIdleConns(0)  there is no open and idle connections.

**Comment by nakagami** [comment]
We manage the number of connections around here, but I believe it is a driver-independent process.
https://github.com/golang/go/blob/master/src/database/sql/sql.go#L958

**Comment by andrewkip** [comment]
Sorry it was my fault! Everything works fine. Sorry again.
