### ISSUE TITLE
Prepared statements (Insert, Update, Delete) are not commited on Exec()

### ISSUE THREAD

**Issue by railsmechanic** [nakagami/firebirdsql#16]
I might have found an issue with prepared statements which gets not commited on Exec().
If I try to execute TestIssue7 of your `driver_test.go` file the code seems to work, but the newly inserted row is not committed. This is the code:
```go
	conn, _ := sql.Open("firebirdsql_createdb", "sysdba:masterkey@localhost:3050/tmp/go_test_issue7.fdb")
	conn.Exec("CREATE TABLE test_issue7 (f1 varchar(2048))")
	defer conn.Close()

	stmt, _ := conn.Prepare("INSERT INTO test_issue7 values (?)")
	stmt.Exec(fmt.Sprintf("%2000d", 1))
```
After executing this code I use isql to connect to the database and submit a `SELECT * FROM test_issue7;` query. The result is empty. Is this an issue or expected behavior or should we use prepared statements only within an extra "wrapping" transaction like the following code snipped?

```go
	conn, _ := sql.Open("firebirdsql_createdb", "sysdba:masterkey@localhost:3050/tmp/go_test_issue7.fdb")
	conn.Exec("CREATE TABLE test_issue7 (f1 varchar(2048))")
	defer conn.Close()

	tx, _ := conn.Begin()
	stmt, _ := tx.Prepare("INSERT INTO test_issue7 values (?)")
	stmt.Exec(fmt.Sprintf("%2000d", 1))
	tx.Commit()
```

Tests with golang drivers for MySQL or PostgreSQL shows, that a prepared statement is commited on Exec without the need of an extra transaction "wrapping" the prepared statement.

**Comment by nakagami** [comment]
Please test with current master.
