### ISSUE TITLE
Error op_response inserting rows with large blobs

### ISSUE THREAD

**Issue by rowland** [nakagami/firebirdsql#18]
Inserting rows larger than 64K *including blobs* results in an error. It appears that blobs are being written like VARCHARs rather than a blob being created and its ID included in the row.

```
func blobOfSize(size int) []byte {
	var buf bytes.Buffer
	for i := 0; i < size; i++ {
		buf.WriteRune('A')
	}
	return buf.Bytes()
}

func TestInsertLargeBlob(t *testing.T) {
	conn, _ := sql.Open("firebirdsql_createdb", "sysdba:masterkey@localhost:3050/tmp/go_test_insert_large_blob.fdb")
	conn.Exec("CREATE TABLE test_blobs (f1 BLOB SUB_TYPE 1)")
	defer conn.Close()

	b0 := blobOfSize(65533)
	if _, err := conn.Exec("INSERT INTO test_blobs (f1) values (?)", b0); err != nil {
		t.Fatalf("Error inserting blobs with params: %v", err)
	}

	var b []byte
	err := conn.QueryRow("SELECT f1 from test_blobs").Scan(&b)
	if err != nil {
		t.Fatalf("Error in query: %v", err)
	}
	if !reflect.DeepEqual(b, b0) {
		t.Fatalf("Binary blob: expected <%v>, got <%v> (%s)", b0, b, string(b))
	}
}
```

**Comment by nakagami** [comment]
fixed

**Comment by rowland** [comment]
I am so sorry, but in my comment above (which I just edited), I had the constant 65532, which is the largest blob which can successfully be inserted, rather than 65533 or higher, which cause an error:

--- FAIL: TestInsertLargeBlob (0.34s)
	driver_test.go:286: Error inserting blobs with params: Error op_response
--- FAIL: TestAccounts (0.00s)
	ids_test.go:19: Error QueryRow: opAccept() protocol error

The driver is still running up against Firebird's row size limit.

**Comment by nakagami** [comment]
Probably fixed

**Comment by rowland** [comment]
Thank you! It is working for me now.
