### ISSUE TITLE
Implicit support to boolean values

### ISSUE THREAD

**Issue by henryx** [nakagami/firebirdsql#19]
Currently Firebird doesn't support BOOLEAN data type. So, insert a boolean value return op_response error. Is a good idea to convert implicitly boolean values into int values when inserting data (other languages support this behaviour)

**Comment by nakagami** [comment]
Firebird3.0 will support boolean value.
So, boolean value convert to FB3's bool parameter.

**Comment by henryx** [comment]
I'm sorry if I reply to this only today. My request is for Firebird 2.x (I know that Firebird 3 has BOOLEAN data type, but it isn't already released for production use). As i mentioned, other languages (such Java) performs an implicit conversion to int before insert the data. It would be nice that this driver perform the same conversion. Anyway, thank you for your work
