### ISSUE TITLE
Wrong logic for handling large BLOBs?

### ISSUE THREAD

**Issue by movermeyer** [nakagami/firebirdsql#20]
Shouldn't [line 441 of wireprotocol.go](https://github.com/nakagami/firebirdsql/blob/c64c5160909912c4bd2444970052880ab39b1c44/wireprotocol.go) be

    for more_data == 1 {

instead of

    for more_data != 2 {

I'm finding that the protocol will return a 0 instead of a 1 every 507873 bytes (strange number).
As a result of this logic, my BLOB is being truncated.

I haven't been able to prove that 0 is an OK response as I can't find the spec and reading the Firebird Server C++ code isn't my strong suit. But changing it seems to work.

Your input would help a lot.

P.S: I noticed that the same logic is also found in [your Python version](https://github.com/nakagami/pyfirebirdsql/blob/b6cbf6ea6cb232294d4f4470948656889134ac69/firebirdsql/fbcore.py#L204)
I've filed a [similar issue there.](https://github.com/nakagami/pyfirebirdsql/issues/58)

**Comment by nakagami** [comment]
Thanks!
