### ISSUE TITLE
[Question] Specifying Transaction settings

### ISSUE THREAD

**Issue by greeny1000** [nakagami/firebirdsql#22]
Hi,
Is it possible to specify the transaction settings/isolation level?
Thanks

**Comment by nakagami** [comment]
You can use 'isolation_level' parameter in connection()

See
https://github.com/nakagami/pyfirebirdsql/blob/master/firebirdsql/consts.py#L149

**Comment by dshumko** [comment]
Sorry, but I don't understand how set isolation_level.
Do you show how level set?

**Comment by nakagami** [comment]
Oh! sorry, I mix with another driver.
This driver still not implement isolation leve.

Please wait, I will implement.

**Comment by nakagami** [comment]
use isolation_level parameter like https://github.com/nakagami/firebirdsql/blob/master/utils_test.go#L52
