### ISSUE TITLE
"invalid transaction handle" after transaction and subsequent select statement

### ISSUE THREAD

**Issue by mrauh** [nakagami/firebirdsql#23]
Maybe this is related to #16.

After a successful transaction, if I select something afterwards, I get the following error (on windows and linux, with Go 1.4.2 and 1.5 RC1):

<em>invalid transaction handle (expecting explicit transaction start)</em>

Here is a minimal example:

```go
tx, err := db.Begin()
if err != nil {
    log.Fatal(err)
}

sqlStr := "INSERT INTO MYTABLE (NAME) VALUES (?)"
if _, err := tx.Exec(sqlStr, "test"); err != nil {
    tx.Rollback()
    log.Fatal(err)
}

if err := tx.Commit(); err != nil {
    log.Fatal(err)
}

var name string
sqlStr = "SELECT NAME FROM MYTABLE WHERE ID = 1"
if err = db.QueryRow(sqlStr).Scan(&name); err != nil {
    log.Fatal(err) // <- invalid transaction handle
}
```
The same code works with other drivers.
Really helpful library, btw! :+1:

**Comment by nakagami** [comment]
Please test with current master.

**Comment by mrauh** [comment]
The current master fixes the problem. Thanks very much!!
