### ISSUE TITLE
support for embedded database

### ISSUE THREAD

**Issue by subroto** [nakagami/firebirdsql#24]
I need to deploy firebirdsql in embedded mode. using isql we can connect just using database filename without host+port. is this feature supported in near future?

**Comment by nakagami** [comment]
Sorry It seems difficul to met. I have no plan.

**Comment by rowland** [comment]
To use Firebird in embedded mode requires fbembed.dll, libfbembed.so or similar, which embed the server in the client. The beauty of firebirdsql is that it is pure Go and speaks the Firebird network protocol without needing to link to a native library.

You may be able to tweak my package https://github.com/rowland/go-fb by changing the linker flags

LDFLAGS: -lfbclient
to
LDFLAGS: -lfbembed

I've not needed this scenario, so I haven't tested it. Also note that go-fb does not implement the database/sql standard, so code changes would be needed.
