### ISSUE TITLE
Query with string parameter

### ISSUE THREAD

**Issue by Shtucer** [nakagami/firebirdsql#28]
Which way should I use for string querying?
For example, I need select from db something like this:

``` SQL
SELECT word FROM words WHERE word LIKE '%suggest%';
```

In Go program I do 

``` Go
queryString := "SELECT word FROM words WHERE word LIKE '%?%'" 
rows, err := db.Query(queryString, "suggest")
```

and that does not work. Selected `words` contains question mark not "suggest" substring.

Fmt works fine:

``` Go
queryString := fmt.Sprintf("SELECT word FROM words WHERE word LIKE '%%%s%%'", "suggest")  
```

but I don't like string manipulation for tihis case...

This question  is firebirdsql driver related?

**Comment by mrotteveel** [comment]
A question mark in a string literal is just a question mark in a string literal; it is not a parameter marker. This is not specific to Firebird, that generically applies to all SQL dialects I know. 

The solution is to use `LIKE '%' || ? || '%'`, that is: use string concatenation (`||`) between two literals with with the wildcard, and the parameter marker. Alternatively, use `LIKE ?` and construct the search pattern in your code instead.
