### ISSUE TITLE
Autoreconnect

### ISSUE THREAD

**Issue by zugl** [nakagami/firebirdsql#29]
Hi there!

Is it possible to implement autoreconnection?

When my database disconnect/restart I get error "Error op_response:0" in the next query after it comes online again (app still running and not reloaded inbetween).

This works in lib/pq and as far as I know should be the standard behavior according to https://golang.org/pkg/database/sql/#Open: 

> The returned DB is safe for concurrent use by multiple goroutines and maintains its own pool of idle connections. Thus, the Open function should be called just once. It is rarely necessary to close a DB.

Thanks in advance, this is a great driver!

**Comment by bat22** [comment]
This driver never return ErrBadConn and a connection pool cant detect bad connection and remove it.

> ErrBadConn should be returned by a driver to signal to the sql package that a driver.Conn is in a bad state (such as the server having earlier closed the connection) and the sql package should retry on a new connection.
> 
> To prevent duplicate operations, ErrBadConn should NOT be returned if there's a possibility that the database server might have performed the operation. Even if the server sends back an error, you shouldn't return ErrBadConn. 

I think next methods candidate for this: 
- wireProtocol.sendPackets
- wireProtocol.recvPackets
- newWireProtocol

But errors returned from sendPackets/recvPackets always ignored.

**Comment by nakagami** [comment]
Is it resolved ?

**Comment by NilsKrause** [comment]
I am using for about two weeks now and it seems to work. Also worked in my tests.
I'd vote for a close, can be reopend if any issues arise.
