### ISSUE TITLE
Exec: when using transaction - always commit(rollback not working)

### ISSUE THREAD

**Issue by arteev** [nakagami/firebirdsql#33]
Problem code??
file: statement.go
line 80: 	err = stmt.tx.Commit()

**Comment by nakagami** [comment]
Uum, yes I think something wrong.
I will fix it

**Comment by nakagami** [comment]
Next, I will add test

**Comment by nakagami** [comment]
https://github.com/nakagami/firebirdsql/blob/master/transaction_test.go
