### ISSUE TITLE
Firebird Events

### ISSUE THREAD

**Issue by arteev** [nakagami/firebirdsql#34]
Hi there!

Is it possible to implement Firebird Events??

**Comment by nakagami** [comment]
No

Because golang sql package interface is not support event.

**Comment by heri16** [comment]
I think this issue would be reopened. Events could be supported.

**Comment by nakagami** [comment]
I see, reopened.

I want  someone's proposal about event support functions.

**Comment by heri16** [comment]
I suggest the idiomatic way: registering go channels using addFBEvent(name) (inspired by: https://github.com/xdenser/node-firebird-libfbclient)

Or better still a way to capture all firebird events into a single channel regardless the event name (however, I am not sure the underlying protocol allows for this.)

**Comment by iambudi** [comment]
Any update about this?

**Comment by nakagami** [comment]
No
I do'nt have good design interface.
Go does not have standard interface abount event notification.

I hope someones pull request

**Comment by jacobalberty** [comment]
Just to provide some documentation about the events  protocol https://github.com/hgourvest/node-firebird/files/737620/FirebirdWireProtocol.pdf  provides some documentation on the wire protocol for events. It is something I would like to look into implementing but in case I never get around to it I thought I should provide the documentation I'm using here.

**Comment by arteev** [comment]
I am doing a `Firebird Event` implementation. Remained architecture design and tests. I will make a merge request soon.
