### ISSUE TITLE
Not properly work after transaction

### ISSUE THREAD

**Issue by heretic13** [nakagami/firebirdsql#35]
`package main

import (
	"database/sql"
	"log"

	_ "github.com/nakagami/firebirdsql"
)

func main() {

	conn, err := sql.Open("firebirdsql", "SYSDBA:masterkey@127.0.0.1/d:/Temp/TestDatabases/TEST.FDB")
	defer conn.Close()

	if err != nil {
		log.Fatal(err)
	}

	// контроль связи с БД
	err = conn.Ping()
	if err != nil {
		log.Fatal(err)
	}

	tx, err := conn.Begin()

	if err != nil {
		log.Fatal(err)
	}

	err = tx.Commit()

	if err != nil {
		log.Fatal(err)
	}

	const query = `CREATE TABLE SensorLog(SN INTEGER NOT NULL);`

	_, err = conn.Exec(query)

	if err != nil {
		log.Fatal(err)
	}
}`

**Comment by heretic13** [comment]
Table not created after transaction.
If I comment transaction it's working.

This is normal?

**Comment by heretic13** [comment]
maybe problem in this

connection.go:

func (fc *firebirdsqlConn) Begin() (driver.Tx, error) {
	**fc.isAutocommit = false**
}

func (fc *firebirdsqlConn) Exec(query string, args []driver.Value) (result driver.Result, err error) {
	**if fc.isAutocommit {
		fc.tx.Commit()
		fc.tx, err = newFirebirdsqlTx(fc.wp, fc.isolationLevel)
	}**
}

**Comment by heretic13** [comment]
After transaction rollback or commit nothing changed in connection state (isAutocommit value).

**Comment by nakagami** [comment]
Thanks, I realize something wrong.

- Begin() make isAutocommit = false
- Commit() and Rollback() are not revert isAutcommit.

I think that changing isAutcommit state in Begin() is evil.
But still I don't know how to fix this problem now.
Wait for a few days. (or send pull request).

**Comment by nakagami** [comment]
I have been modify and refactoring, and add test codes.
https://github.com/nakagami/firebirdsql/blob/master/transaction_test.go

I think, this problem fixed. 
Please test it with master HEAD.

**Comment by heretic13** [comment]
I checked. This solution does not work.
Tested by example, which I quoted above.
Begin () makes the transaction with property tx.isAutocommit = false.
When I do a tx.Commit() - nothing changes.

If I do then conn.Exec ():

if fc.isAutocommit && fc.tx.isAutocommit {
fc.tx.Commit ()
}

fc.isAutocommit = true
fc.tx.isAutocommit = false

fc.tx.Commit () - not performed

**Comment by heretic13** [comment]
I think that once executed tx.Commit () or tx.Rollback () the connection must be changed fc.tx.isAutocommit flag or forget the old transaction and create a new transaction for its own needs (as is done in newFirebirdsqlConn ())

**Comment by nakagami** [comment]
Thanks, 
I think I wrote regression test and fix code.

Restart transaction in Commit() and Rollback()
Is this OK ?

**Comment by heretic13** [comment]
Hmm... It's working!

**Comment by nakagami** [comment]
thanks
