### ISSUE TITLE
Unavailable database using wire_crypt=false

### ISSUE THREAD

**Issue by giovannigaspar** [nakagami/firebirdsql#52]
I changed my firebird.conf file to "WireCrypt = Disabled" and restarted my server. From python, I could connect to database as usual, but from "GO", even using "wire_crypt=false" as a parameter, it says: "unavailable database". 

If i change firebird.conf to "WireCrypt = Enabled"  and GO to  "wire_crypt=true" it works, cuz that's the default for firebird 3.

Thanks.

**Comment by nakagami** [comment]
I hope fixed at master.
Please try with master HEAD
