### ISSUE TITLE
Error op_response:0 in next query

### ISSUE THREAD

**Issue by Kirill** [nakagami/firebirdsql#71]
Hi. I test rewrite this simple web-app https://grisha.org/blog/2017/04/27/simplistic-go-web-app/ for Firebird. I have DB with some data. I have project writing with article analog https://gitlab.com/krak/test.
If I get http://127.0.0.1/carrier I recieve json string with data. If I refresh this page - take this data again I get error **Error op_response:0**.
This error I can see in debug https://gitlab.com/krak/test/blob/master/db/firebird.go#L69
I see this error in other issue #29, but I don't sure that's equal problem.

**Comment by nakagami** [comment]
Is this issue related to #76 ?

**Comment by bat22** [comment]
> Is this issue related to #76 ?

Message "Error op_response:0" may be related with #76. But root cause for this error - statement always closes with mode 2 (DSQL_drop) and the second call smt.Query/stmt.Exec fails because statement already dropped on server side.

I try to make patch this week
