### ISSUE TITLE
github.com/nyarla/go-crypt dependency has gone missing

### ISSUE THREAD

**Issue by alemenke** [nakagami/firebirdsql#72]
The github.com/nyarla/go-crypt import in wireprotocol.go isn't available anymore and breaks building anything using this library. The author has removed the repository and seems to have moved it to GitLab: https://gitlab.com/nyarla/go-crypt

The homepage of the author (https://nyarla.net/) lists 
>GitLab: @nyarla (開発・移住した)
>GitHub: @nyarla (開発・停止中) 

Google Translate:
>GitLab: @nyarla (developed / immigrated)
>GitHub: @nyarla (under development / stop)

**Comment by nakagami** [comment]
Thanks
