### ISSUE TITLE
Error op_reject

### ISSUE THREAD

**Issue by ZzEeKkAa** [nakagami/firebirdsql#74]
Hi, everyone. I know, that firebird 1.5.6 is not supported by this library, but it seems, like it's working on base level. I just have issue with connection. After successful connection, in some cases, I have not working one. Any query on this connection returns "_parse_connect_response() op_reject" error. But if it is successful, there is no error in any next queries. So current workaround for me is:
```go
for{
  connect()
  if ping(){ break; }
  close()
}
defer close()

// do my stuff
```
it takes 4-7 times to establish good connection.
Does anybody has a clue how to trace this issue?

BTW: database is ok, since I can connect to it with isql without any trouble.

**Comment by nakagami** [comment]
Sorry Firebird 1.5 is not supported
