### ISSUE TITLE
Ping doesn't work as expected

### ISSUE THREAD

**Issue by dimkouv** [nakagami/firebirdsql#82]
When the database gets stopped, connection.Ping() doesn't work as expected.

```go
// Ping verifies a connection to the database is still alive,
// establishing a connection if necessary.
func (db *DB) Ping() error {
```

No error is returned and the connection isn't re-established if the database is started again.

Reproducing...
```go
conn, err = sql.Open("firebirdsql", "connection/string/here")
for {
    fmt.Printf(">>> %v \n", conn.Ping())
    time.Sleep(2 * time.Second)
}
```

```bash
systemctl stop firebirdsql
sleep 5
systemctl start firebirdsql
```

**Comment by bat22** [comment]
As i see, Ping() not implemented
https://github.com/nakagami/firebirdsql/blob/master/driver_go18.go#L88
