### ISSUE TITLE
Error establishing connection: dial tcp: missing address

### ISSUE THREAD

**Issue by ArthurZ** [nakagami/firebirdsql#84]
Hi there,
I am getting the following error connecting to a local Firebird 3.0 on Win 10:
`dial tcp: missing address`
The conn string looks as follows:
`sql.Open("firebirdsql", "myuser:mypwd@localhost/C://db//firebird//syncverifier//SYNCVERIFIER.FDB")`

**Comment by nakagami** [comment]
Probabry
`sql.Open("firebirdsql", "myuser:mypwd@localhost/C:/db/firebird/syncverifier/SYNCVERIFIER.FDB")`
