### ISSUE TITLE
Request to create/drop database

### ISSUE THREAD

**Issue by tredoe** [nakagami/firebirdsql#97]
Could be added the API to create/drop a database?

**Comment by nakagami** [comment]
If you want to create database, use `firebirdsql_createdb` driver name  
```
sql.Open('firebirdsql_createdb',  ...) 
```
On the other hand,  I think drop database api is do'es not work if it is implemented.

**Comment by tredoe** [comment]
Well, the file can be deleted directly to drop the database; so, it is not necessary to change the API.
