### ISSUE TITLE
Embedded database

### ISSUE THREAD

**Issue by tredoe** [nakagami/firebirdsql#98]
The driver does not allow a connection to an embedded database.

**Comment by bat22** [comment]
This package is a pure golang implementation of firebird network protocol without libfbclient/libfbembed dependency. It requires a running firebird server.
To connect to an embedded database from golang you need to wrap libfbembed library.

**Comment by tredoe** [comment]
Could you add that information at the documentation?

**Comment by bat22** [comment]
Unfortunately I am not familiar with this.
If you want to do it yourself i think you need to start with cgo. 
You can also see https://github.com/rowland/go-fb as an example of wrapping libfbclient.

**Comment by tredoe** [comment]
Neither me; I don't use C.

**Comment by nakagami** [comment]
Sorry, there are no plans to support embedded server
